automation:
  - alias: Turn on Deck Lights at Sunset
    trigger:
      platform: sun
      event: sunset
      #offset: '-00:00:00'
    action:
      service: light.turn_on
      entity_id: light.porch_light

  - alias: Turn off Deck Lights at Sunrise
    trigger:
      platform: sun
      event: sunrise
      #offset: '-00:00:00'
    action:
      service: light.turn_off
      entity_id: light.porch_light
