homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Australia/Melbourne

  customize:
    media_player.bathroom:
      entity_picture: ''
    media_player.deck:
      entity_picture: ''
    media_player.lounge:
      entity_picture: ''

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password

# Checks for available updates
updater:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

light:
  - platform: lifx

media_player:
  - platform: sonos
  - platform: roku

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

wemo:

camera:
  - platform: uvc
    nvr: !secret unifi_ip
    key: !secret unifi_api
    port: !secret unifi_port
    password: !secret unifi_password

group: !include groups.yaml
automation: !include automations.yaml